# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'baratie.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, -1, 121, 111))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("imagens/logo.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 801, 111))
        self.label_3.setStyleSheet("QLabel{\n"
"    background-color: rgb(248, 248, 248);\n"
"}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-4, 2, 821, 571))
        self.label_4.setStyleSheet("QLabel{\n"
"    background-color: rgb(245, 233, 199);\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 130, 761, 411))
        self.label.setStyleSheet("QLabel{\n"
"    background-color: rgb(248, 248, 248)\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 150, 721, 371))
        self.label_5.setStyleSheet("QLabel{\n"
"    border: 3px solid rgb(235, 173, 49)\n"
"}")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 170, 101, 101))
        self.label_6.setStyleSheet("QLabel{\n"
"    border: 3px solid rgb(235, 173, 49)\n"
"}")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("imagens/panqueca.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 290, 101, 101))
        self.label_7.setStyleSheet("QLabel{\n"
"    border: 3px solid rgb(235, 173, 49)\n"
"}")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("imagens/cagou.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(390, 170, 101, 101))
        self.label_8.setStyleSheet("QLabel{\n"
"    border: 3px solid rgb(235, 173, 49)\n"
"}")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("imagens/lagosta.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(390, 290, 101, 101))
        self.label_9.setStyleSheet("QLabel{\n"
"    border: 3px solid rgb(235, 173, 49)\n"
"}")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("imagens/vodka2.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(170, 170, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(18)
        font.setItalic(True)
        font.setUnderline(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel{\n"
"    color: rgb(75, 56, 15);\n"
"}")
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(500, 170, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(18)
        font.setItalic(True)
        font.setUnderline(True)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel{\n"
"    color: rgb(75, 56, 15);\n"
"}")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(500, 290, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(18)
        font.setItalic(True)
        font.setUnderline(True)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel{\n"
"    color: rgb(75, 56, 15);\n"
"}")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(170, 290, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(18)
        font.setItalic(True)
        font.setUnderline(True)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel{\n"
"    color: rgb(75, 56, 15);\n"
"}")
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(170, 340, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(22)
        font.setItalic(True)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel{\n"
"    color: rgb(75, 56, 15);\n"
"}")
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(170, 220, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(22)
        font.setItalic(True)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel{\n"
"    color: rgb(75, 56, 15);\n"
"}")
        self.label_15.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(500, 220, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(22)
        font.setItalic(True)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel{\n"
"    color: rgb(75, 56, 15);\n"
"}")
        self.label_16.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(498, 340, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(22)
        font.setItalic(True)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel{\n"
"    color: rgb(75, 56, 15);\n"
"}")
        self.label_17.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(290, 420, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(24)
        font.setItalic(True)
        font.setUnderline(True)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("QLabel{\n"
"    color: rgb(75, 56, 15);\n"
"}")
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(307, 350, 75, 41))
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(16)
        font.setItalic(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(248, 248, 248);\n"
"    border: 3px solid rgb(235, 173, 49);\n"
"    color: rgb(75, 56, 15);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(245, 233, 199);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(307, 230, 75, 41))
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(16)
        font.setItalic(True)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("QPushButton{\n"
"    background-color: rgb(248, 248, 248);\n"
"    border: 3px solid rgb(235, 173, 49);\n"
"    color: rgb(75, 56, 15);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(245, 233, 199);\n"
"}")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(680, 230, 75, 41))
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(16)
        font.setItalic(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color: rgb(248, 248, 248);\n"
"    border: 3px solid rgb(235, 173, 49);\n"
"    color: rgb(75, 56, 15);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(245, 233, 199);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(680, 350, 75, 41))
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(16)
        font.setItalic(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background-color: rgb(248, 248, 248);\n"
"    border: 3px solid rgb(235, 173, 49);\n"
"    color: rgb(75, 56, 15);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(245, 233, 199);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_total = QtWidgets.QLabel(self.centralwidget)
        self.label_total.setGeometry(QtCore.QRect(420, 420, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(24)
        font.setItalic(True)
        font.setUnderline(True)
        self.label_total.setFont(font)
        self.label_total.setStyleSheet("QLabel{\n"
"    color: rgb(75, 56, 15);\n"
"}")
        self.label_total.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_total.setWordWrap(True)
        self.label_total.setObjectName("label_total")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(310, 460, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(18)
        font.setItalic(True)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    background-color: rgb(248, 248, 248);\n"
"    border: 3px solid rgb(235, 173, 49);\n"
"    color: rgb(75, 56, 15);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(245, 233, 199);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_4.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.pushButton_2.raise_()
        self.pushButton_1.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.label_total.raise_()
        self.pushButton_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setText(_translate("MainWindow", "Frittella di Gamberetti"))
        self.label_11.setText(_translate("MainWindow", "La malvagia aragosta blu"))
        self.label_12.setText(_translate("MainWindow", "Billionaire Vodka"))
        self.label_13.setText(_translate("MainWindow", "Escargot"))
        self.label_14.setText(_translate("MainWindow", "R$ 799,90"))
        self.label_15.setText(_translate("MainWindow", "R$ 53,90"))
        self.label_16.setText(_translate("MainWindow", "R$ 2000.00"))
        self.label_17.setText(_translate("MainWindow", "R$ 3.700.000,00"))
        self.label_18.setText(_translate("MainWindow", "Total: R$"))
        self.pushButton_2.setText(_translate("MainWindow", "Comprar"))
        self.pushButton_1.setText(_translate("MainWindow", "Comprar"))
        self.pushButton_3.setText(_translate("MainWindow", "Comprar"))
        self.pushButton_4.setText(_translate("MainWindow", "Comprar"))
        self.label_total.setText(_translate("MainWindow", "00,00"))
        self.pushButton_5.setText(_translate("MainWindow", "Pedir Conta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
