# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checarNotas.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(200, 20, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.tableWidget_notas = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_notas.setGeometry(QtCore.QRect(70, 71, 661, 451))
        self.tableWidget_notas.setObjectName("tableWidget_notas")
        self.tableWidget_notas.setColumnCount(6)
        self.tableWidget_notas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_notas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_notas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_notas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_notas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_notas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_notas.setHorizontalHeaderItem(5, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setText(_translate("MainWindow", "Notas dos Candidatos"))
        item = self.tableWidget_notas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "CPF"))
        item = self.tableWidget_notas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "N_P"))
        item = self.tableWidget_notas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "N_M"))
        item = self.tableWidget_notas.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "N_CG"))
        item = self.tableWidget_notas.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "N_CE"))
        item = self.tableWidget_notas.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Média"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
