# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cinema.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 90, 181, 251))
        self.label.setStyleSheet("QLabel{\n"
"    border-radius: 10px;\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imagens/abelhinhas.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 90, 181, 251))
        self.label_2.setStyleSheet("QLabel{\n"
"    border-top-left-radius: 10px;\n"
"}")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("imagens/barquinhos.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 90, 181, 251))
        self.label_3.setStyleSheet("QLabel{\n"
"    border-top-left-radius: 10px;\n"
"}")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("imagens/Ratatoing.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(600, 90, 181, 251))
        self.label_4.setStyleSheet("QLabel{\n"
"    border-top-left-radius: 10px;\n"
"}")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("imagens/urso.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton_resumo1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_resumo1.setGeometry(QtCore.QRect(30, 340, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.pushButton_resumo1.setFont(font)
        self.pushButton_resumo1.setStyleSheet("QPushButton{\n"
"color: rgb(225, 255, 250);\n"
"background-color: rgb(0, 19, 131);\n"
"border-bottom-left-radius: 20px;\n"
"border-right: 3px solid rgb(24, 0, 72);\n"
"}")
        self.pushButton_resumo1.setObjectName("pushButton_resumo1")
        self.pushButton_sessoes1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sessoes1.setGeometry(QtCore.QRect(120, 340, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.pushButton_sessoes1.setFont(font)
        self.pushButton_sessoes1.setStyleSheet("QPushButton{\n"
"color: rgb(225, 255, 250);\n"
"background-color: rgb(0, 19, 131);\n"
"border-bottom-right-radius: 20px;\n"
"}")
        self.pushButton_sessoes1.setObjectName("pushButton_sessoes1")
        self.pushButton_resumo2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_resumo2.setGeometry(QtCore.QRect(220, 340, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.pushButton_resumo2.setFont(font)
        self.pushButton_resumo2.setStyleSheet("QPushButton{\n"
"color: rgb(225, 255, 250);\n"
"background-color: rgb(0, 19, 131);\n"
"border-bottom-left-radius: 20px;\n"
"border-right: 3px solid rgb(24, 0, 72);\n"
"}")
        self.pushButton_resumo2.setObjectName("pushButton_resumo2")
        self.pushButton_sessoes2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sessoes2.setGeometry(QtCore.QRect(310, 340, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.pushButton_sessoes2.setFont(font)
        self.pushButton_sessoes2.setStyleSheet("QPushButton{\n"
"color: rgb(225, 255, 250);\n"
"background-color: rgb(0, 19, 131);\n"
"border-bottom-right-radius: 20px;\n"
"}")
        self.pushButton_sessoes2.setObjectName("pushButton_sessoes2")
        self.pushButton_resumo3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_resumo3.setGeometry(QtCore.QRect(410, 340, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.pushButton_resumo3.setFont(font)
        self.pushButton_resumo3.setStyleSheet("QPushButton{\n"
"color: rgb(225, 255, 250);\n"
"background-color: rgb(0, 19, 131);\n"
"border-bottom-left-radius: 20px;\n"
"border-right: 3px solid rgb(24, 0, 72);\n"
"}")
        self.pushButton_resumo3.setObjectName("pushButton_resumo3")
        self.pushButton_sessoes3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sessoes3.setGeometry(QtCore.QRect(500, 340, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.pushButton_sessoes3.setFont(font)
        self.pushButton_sessoes3.setStyleSheet("QPushButton{\n"
"color: rgb(225, 255, 250);\n"
"background-color: rgb(0, 19, 131);\n"
"border-bottom-right-radius: 20px;\n"
"}")
        self.pushButton_sessoes3.setObjectName("pushButton_sessoes3")
        self.pushButton_resumo4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_resumo4.setGeometry(QtCore.QRect(600, 340, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.pushButton_resumo4.setFont(font)
        self.pushButton_resumo4.setStyleSheet("QPushButton{\n"
"color: rgb(225, 255, 250);\n"
"background-color: rgb(0, 19, 131);\n"
"border-bottom-left-radius: 20px;\n"
"border-right: 3px solid rgb(24, 0, 72);\n"
"}")
        self.pushButton_resumo4.setObjectName("pushButton_resumo4")
        self.pushButton_sessoes4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sessoes4.setGeometry(QtCore.QRect(690, 340, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.pushButton_sessoes4.setFont(font)
        self.pushButton_sessoes4.setStyleSheet("QPushButton{\n"
"color: rgb(225, 255, 250);\n"
"background-color: rgb(0, 19, 131);\n"
"border-bottom-right-radius: 20px;\n"
"}")
        self.pushButton_sessoes4.setObjectName("pushButton_sessoes4")
        self.label_sinopse1 = QtWidgets.QLabel(self.centralwidget)
        self.label_sinopse1.setGeometry(QtCore.QRect(40, 400, 161, 141))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.label_sinopse1.setFont(font)
        self.label_sinopse1.setStyleSheet("QLabel{\n"
"\n"
"color: rgb(225, 255, 250);\n"
"\n"
"}")
        self.label_sinopse1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_sinopse1.setWordWrap(True)
        self.label_sinopse1.setObjectName("label_sinopse1")
        self.label_sinopse2 = QtWidgets.QLabel(self.centralwidget)
        self.label_sinopse2.setGeometry(QtCore.QRect(230, 400, 161, 141))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.label_sinopse2.setFont(font)
        self.label_sinopse2.setStyleSheet("QLabel{\n"
"color: rgb(225, 255, 250);\n"
"\n"
"}")
        self.label_sinopse2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_sinopse2.setWordWrap(True)
        self.label_sinopse2.setObjectName("label_sinopse2")
        self.label_sinopse3 = QtWidgets.QLabel(self.centralwidget)
        self.label_sinopse3.setGeometry(QtCore.QRect(420, 400, 161, 141))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.label_sinopse3.setFont(font)
        self.label_sinopse3.setStyleSheet("QLabel{\n"
"color: rgb(225, 255, 250);\n"
"}")
        self.label_sinopse3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_sinopse3.setWordWrap(True)
        self.label_sinopse3.setObjectName("label_sinopse3")
        self.label_sinopse4 = QtWidgets.QLabel(self.centralwidget)
        self.label_sinopse4.setGeometry(QtCore.QRect(610, 400, 161, 141))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(9)
        self.label_sinopse4.setFont(font)
        self.label_sinopse4.setStyleSheet("QLabel{\n"
"color: rgb(225, 255, 250);\n"
"}")
        self.label_sinopse4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_sinopse4.setWordWrap(True)
        self.label_sinopse4.setObjectName("label_sinopse4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 811, 561))
        self.label_9.setStyleSheet("QLabel{\n"
"    background-color: rgb(235, 235, 235)\n"
"}")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 811, 71))
        self.label_10.setStyleSheet("QLabel{\n"
"    background-color:rgb(161, 219, 255)\n"
"}")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(330, 3, 151, 51))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("imagens/logo.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(360, 43, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel{\n"
"    color: rgb(197, 13, 33);\n"
"}")
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setObjectName("label_12")
        self.label_fundo1 = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo1.setGeometry(QtCore.QRect(30, 390, 181, 161))
        self.label_fundo1.setStyleSheet("QLabel{\n"
"background-color: rgb(0, 19, 131);\n"
"border-radius: 20px\n"
"}")
        self.label_fundo1.setText("")
        self.label_fundo1.setObjectName("label_fundo1")
        self.label_fundo2 = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo2.setGeometry(QtCore.QRect(220, 390, 181, 161))
        self.label_fundo2.setStyleSheet("QLabel{\n"
"background-color: rgb(0, 19, 131);\n"
"border-radius: 20px\n"
"}")
        self.label_fundo2.setText("")
        self.label_fundo2.setObjectName("label_fundo2")
        self.label_fundo3 = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo3.setGeometry(QtCore.QRect(410, 390, 181, 161))
        self.label_fundo3.setStyleSheet("QLabel{\n"
"background-color: rgb(0, 19, 131);\n"
"border-radius: 20px\n"
"}")
        self.label_fundo3.setText("")
        self.label_fundo3.setObjectName("label_fundo3")
        self.label_fundo4 = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo4.setGeometry(QtCore.QRect(600, 390, 181, 161))
        self.label_fundo4.setStyleSheet("QLabel{\n"
"background-color: rgb(0, 19, 131);\n"
"border-radius: 20px\n"
"}")
        self.label_fundo4.setText("")
        self.label_fundo4.setObjectName("label_fundo4")
        self.label_9.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.pushButton_resumo1.raise_()
        self.pushButton_sessoes1.raise_()
        self.pushButton_resumo2.raise_()
        self.pushButton_sessoes2.raise_()
        self.pushButton_resumo3.raise_()
        self.pushButton_sessoes3.raise_()
        self.pushButton_resumo4.raise_()
        self.pushButton_sessoes4.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_fundo1.raise_()
        self.label_sinopse1.raise_()
        self.label_fundo2.raise_()
        self.label_sinopse2.raise_()
        self.label_fundo3.raise_()
        self.label_sinopse3.raise_()
        self.label_fundo4.raise_()
        self.label_sinopse4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_resumo1.setText(_translate("MainWindow", "Resumo"))
        self.pushButton_sessoes1.setText(_translate("MainWindow", "Sessões"))
        self.pushButton_resumo2.setText(_translate("MainWindow", "Resumo"))
        self.pushButton_sessoes2.setText(_translate("MainWindow", "Sessões"))
        self.pushButton_resumo3.setText(_translate("MainWindow", "Resumo"))
        self.pushButton_sessoes3.setText(_translate("MainWindow", "Sessões"))
        self.pushButton_resumo4.setText(_translate("MainWindow", "Resumo"))
        self.pushButton_sessoes4.setText(_translate("MainWindow", "Sessões"))
        self.label_sinopse1.setText(_translate("MainWindow", "Uma abelha sonha em se tornar uma guerreira, mas quando consegue, sente falta de sua antiga vida."))
        self.label_sinopse2.setText(_translate("MainWindow", "Jota é um Jet Sky muito corajoso e curioso, mas vive se metendo em tremendas confusões em alto mar. É sempre o seu fiel e atrapalhado amigo Beto Bote e sua irmã Lili que o ajudam a sair das enrascadas que ele vive em Oceanópolis."))
        self.label_sinopse3.setText(_translate("MainWindow", "Filme conta a história de Marcell Toing, um rato dono do famoso restaurante Ratatoing. Juntamente com Carol e Greg, ele sai em busca de ingredientes raros nos estabelecimentos dos humanos, enfrentando de ratoeiras a gatos famintos."))
        self.label_sinopse4.setText(_translate("MainWindow", "Pancada é um faxineiro que trabalha no Bear Bar Box e seu maior sonho é estrelar um espetáculo de dança. Quando finalmente consegue dar asas à sua fantasia, seus planos mudam por uma brilhante ideia."))
        self.label_12.setText(_translate("MainWindow", "Cinema"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
