# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 678)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 371, 59, 25))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"color: white\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 421, 58, 25))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"color: white\n"
"}")
        self.label_2.setObjectName("label_2")
        self.lineEdit_titulo = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_titulo.setGeometry(QtCore.QRect(100, 371, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit_titulo.setFont(font)
        self.lineEdit_titulo.setObjectName("lineEdit_titulo")
        self.lineEdit_autor = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_autor.setGeometry(QtCore.QRect(100, 420, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit_autor.setFont(font)
        self.lineEdit_autor.setObjectName("lineEdit_autor")
        self.pushButton_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cadastrar.setGeometry(QtCore.QRect(390, 570, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        self.pushButton_cadastrar.setFont(font)
        self.pushButton_cadastrar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 235, 235);\n"
"border-radius: 20px\n"
"}")
        self.pushButton_cadastrar.setObjectName("pushButton_cadastrar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 520, 186, 25))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"color: white\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(480, 330, 81, 25))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"color: white\n"
"}")
        self.label_4.setObjectName("label_4")
        self.lineEdit_categoria = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_categoria.setGeometry(QtCore.QRect(150, 470, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit_categoria.setFont(font)
        self.lineEdit_categoria.setObjectName("lineEdit_categoria")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 470, 96, 25))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"color: white\n"
"}")
        self.label_5.setObjectName("label_5")
        self.dateEdit_publi = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_publi.setGeometry(QtCore.QRect(230, 520, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dateEdit_publi.setFont(font)
        self.dateEdit_publi.setObjectName("dateEdit_publi")
        self.textEdit_resumo = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_resumo.setGeometry(QtCore.QRect(480, 370, 381, 181))
        self.textEdit_resumo.setObjectName("textEdit_resumo")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 901, 61))
        self.label_6.setStyleSheet("QLabel{\n"
"    background-color: rgb(54, 0, 0)\n"
"}")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(330, 10, 235, 38))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(24)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel{\n"
"    color: rgb(255, 156, 158)\n"
"}")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 60, 901, 261))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("caveira.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(60, 140, 311, 141))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0)\n"
"}")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 320, 911, 341))
        self.label_10.setStyleSheet("QLabel{\n"
"background-color: rgb(62, 0, 0)\n"
"}")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_10.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lineEdit_titulo.raise_()
        self.lineEdit_autor.raise_()
        self.pushButton_cadastrar.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.lineEdit_categoria.raise_()
        self.label_5.raise_()
        self.dateEdit_publi.raise_()
        self.textEdit_resumo.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Título:"))
        self.label_2.setText(_translate("MainWindow", "Autor:"))
        self.pushButton_cadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.label_3.setText(_translate("MainWindow", "Data de Publicação:"))
        self.label_4.setText(_translate("MainWindow", "Resumo:"))
        self.label_5.setText(_translate("MainWindow", "Categoria:"))
        self.dateEdit_publi.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.label_7.setText(_translate("MainWindow", "Bibliteca do Rock"))
        self.label_9.setText(_translate("MainWindow", "CADASTRE SEU LIVRO AGOORAAA!!!!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
