# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2-pause.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Parar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Parar.setGeometry(QtCore.QRect(500, 400, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Parar.setFont(font)
        self.pushButton_Parar.setObjectName("pushButton_Parar")
        self.pushButton_Tocar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Tocar.setGeometry(QtCore.QRect(290, 240, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Tocar.setFont(font)
        self.pushButton_Tocar.setObjectName("pushButton_Tocar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Parar.setText(_translate("MainWindow", "Parar"))
        self.pushButton_Tocar.setText(_translate("MainWindow", "Play"))
