# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pokemonExe.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QPushButton{\n"
"    background-color: rgb(120, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 581))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Pictures/118978.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.labelTitulo = QtWidgets.QLabel(self.centralwidget)
        self.labelTitulo.setGeometry(QtCore.QRect(210, 10, 371, 61))
        font = QtGui.QFont()
        font.setFamily("Snap ITC")
        font.setPointSize(20)
        self.labelTitulo.setFont(font)
        self.labelTitulo.setStyleSheet("QLabel{\n"
"    color: rgb(255, 0, 0)\n"
"}")
        self.labelTitulo.setObjectName("labelTitulo")
        self.labelPersonagem = QtWidgets.QLabel(self.centralwidget)
        self.labelPersonagem.setGeometry(QtCore.QRect(250, 80, 311, 361))
        self.labelPersonagem.setText("")
        self.labelPersonagem.setPixmap(QtGui.QPixmap("../../../Pictures/7ae937b5ded82ae.png"))
        self.labelPersonagem.setScaledContents(True)
        self.labelPersonagem.setObjectName("labelPersonagem")
        self.pushButtonPlay = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPlay.setGeometry(QtCore.QRect(320, 470, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(14)
        self.pushButtonPlay.setFont(font)
        self.pushButtonPlay.setStyleSheet("")
        self.pushButtonPlay.setObjectName("pushButtonPlay")
        self.pushButtonPikachu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPikachu.setGeometry(QtCore.QRect(30, 90, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.pushButtonPikachu.setFont(font)
        self.pushButtonPikachu.setObjectName("pushButtonPikachu")
        self.pushButtonCharmander = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCharmander.setGeometry(QtCore.QRect(30, 150, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(10)
        self.pushButtonCharmander.setFont(font)
        self.pushButtonCharmander.setObjectName("pushButtonCharmander")
        self.pushButtonSquirtle = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSquirtle.setGeometry(QtCore.QRect(30, 210, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.pushButtonSquirtle.setFont(font)
        self.pushButtonSquirtle.setObjectName("pushButtonSquirtle")
        self.pushButtonBulbassauro = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBulbassauro.setGeometry(QtCore.QRect(30, 270, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(10)
        self.pushButtonBulbassauro.setFont(font)
        self.pushButtonBulbassauro.setObjectName("pushButtonBulbassauro")
        self.pushButtonEevee = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEevee.setGeometry(QtCore.QRect(30, 330, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.pushButtonEevee.setFont(font)
        self.pushButtonEevee.setObjectName("pushButtonEevee")
        self.pushButtonHypno = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonHypno.setGeometry(QtCore.QRect(30, 390, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.pushButtonHypno.setFont(font)
        self.pushButtonHypno.setObjectName("pushButtonHypno")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTitulo.setText(_translate("MainWindow", "Escolha seu personagem"))
        self.pushButtonPlay.setText(_translate("MainWindow", "Play"))
        self.pushButtonPikachu.setText(_translate("MainWindow", "Pikachu.exe"))
        self.pushButtonCharmander.setText(_translate("MainWindow", "Charmander.exe"))
        self.pushButtonSquirtle.setText(_translate("MainWindow", "Squirtle.exe"))
        self.pushButtonBulbassauro.setText(_translate("MainWindow", "Bulbassauro.exe"))
        self.pushButtonEevee.setText(_translate("MainWindow", "Eevee.exe"))
        self.pushButtonHypno.setText(_translate("MainWindow", "Hypno.exe"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
