# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReprodutorMusical.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_play = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_play.setGeometry(QtCore.QRect(330, 190, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_play.setFont(font)
        self.pushButton_play.setObjectName("pushButton_play")
        self.pushButton_parar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_parar.setGeometry(QtCore.QRect(330, 250, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_parar.setFont(font)
        self.pushButton_parar.setObjectName("pushButton_parar")
        self.pushButton_pausar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pausar.setGeometry(QtCore.QRect(330, 310, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_pausar.setFont(font)
        self.pushButton_pausar.setObjectName("pushButton_pausar")
        self.horizontalSlider_volume = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_volume.setGeometry(QtCore.QRect(300, 380, 160, 22))
        self.horizontalSlider_volume.setMaximum(100)
        self.horizontalSlider_volume.setProperty("value", 50)
        self.horizontalSlider_volume.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_volume.setObjectName("horizontalSlider_volume")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_play.setText(_translate("MainWindow", "Play"))
        self.pushButton_parar.setText(_translate("MainWindow", "Parar"))
        self.pushButton_pausar.setText(_translate("MainWindow", "Pausar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
