# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alienSimulator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(38, 38, 38);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 20, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 150, 181, 181))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Ben10/Alien X/AlienXUAF.webp"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(450, 140, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("QRadioButton{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(450, 180, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("QRadioButton{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(450, 220, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("QRadioButton{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(450, 260, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setStyleSheet("QRadioButton{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(0, 540, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setStyleSheet("QRadioButton{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.radioButton_5.setObjectName("radioButton_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 340, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"QPushButton{\n"
"    border-radius: 8px;\n"
"    background-color: green;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Quem é o alien fudido do ben 10"))
        self.radioButton.setText(_translate("MainWindow", "Alien X"))
        self.radioButton_2.setText(_translate("MainWindow", "Quatro-braços"))
        self.radioButton_3.setText(_translate("MainWindow", "XLR8"))
        self.radioButton_4.setText(_translate("MainWindow", "Chama"))
        self.radioButton_5.setText(_translate("MainWindow", "Alien X vidros"))
        self.pushButton.setText(_translate("MainWindow", "Selecionar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
