# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 802)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(94, 106, 156, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    color: rgb(216, 231, 255)\n"
"}")
        self.label.setObjectName("label")
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(93, 139, 321, 38))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_nome.setFont(font)
        self.lineEdit_nome.setStyleSheet("QLineEdit{\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"    margin-left: 2px solid rgb(49, 48, 98);\n"
"}")
        self.lineEdit_nome.setText("")
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.pushButton_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cadastrar.setGeometry(QtCore.QRect(630, 680, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Harlow Solid Italic")
        font.setPointSize(18)
        font.setItalic(True)
        self.pushButton_cadastrar.setFont(font)
        self.pushButton_cadastrar.setStyleSheet("QPushButton{\n"
"    background-color:rgb(216, 231, 255);\n"
"color: rgb(0, 0, 76);\n"
"border-radius: 20px\n"
"}")
        self.pushButton_cadastrar.setObjectName("pushButton_cadastrar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(93, 186, 195, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    color: rgb(216, 231, 255)\n"
"}")
        self.label_3.setObjectName("label_3")
        self.dateEdit_nasc = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_nasc.setGeometry(QtCore.QRect(93, 217, 151, 38))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        self.dateEdit_nasc.setFont(font)
        self.dateEdit_nasc.setStyleSheet("QDateEdit{\n"
"    border-radius: 12px;\n"
"padding: 6px\n"
"}")
        self.dateEdit_nasc.setObjectName("dateEdit_nasc")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 20, 771, 731))
        self.label_6.setStyleSheet("QLabel{\n"
"    background-color:rgb(0, 0, 57);\n"
"    border-radius: 20px\n"
"}")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(330, 22, 235, 61))
        font = QtGui.QFont()
        font.setFamily("Harlow Solid Italic")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel{\n"
"    color: rgb(216, 231, 255)\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 911, 791))
        self.label_10.setStyleSheet("QLabel{\n"
"background-color:rgb(49, 48, 98)\n"
"}")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(93, 266, 52, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    color: rgb(216, 231, 255)\n"
"}")
        self.label_2.setObjectName("label_2")
        self.lineEdit_cpf = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_cpf.setGeometry(QtCore.QRect(92, 299, 321, 38))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_cpf.setFont(font)
        self.lineEdit_cpf.setStyleSheet("QLineEdit{\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"    margin-left: 2px solid rgb(49, 48, 98);\n"
"}")
        self.lineEdit_cpf.setText("")
        self.lineEdit_cpf.setObjectName("lineEdit_cpf")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(94, 586, 152, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    color: rgb(216, 231, 255)\n"
"}")
        self.label_4.setObjectName("label_4")
        self.lineEdit_complemento = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_complemento.setGeometry(QtCore.QRect(93, 619, 321, 38))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_complemento.setFont(font)
        self.lineEdit_complemento.setStyleSheet("QLineEdit{\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"}")
        self.lineEdit_complemento.setText("")
        self.lineEdit_complemento.setObjectName("lineEdit_complemento")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 106, 68, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"    color: rgb(216, 231, 255)\n"
"}")
        self.label_5.setObjectName("label_5")
        self.lineEdit_bairro = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_bairro.setGeometry(QtCore.QRect(479, 139, 321, 38))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_bairro.setFont(font)
        self.lineEdit_bairro.setStyleSheet("QLineEdit{\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"    margin-left: 2px solid rgb(49, 48, 98);\n"
"}")
        self.lineEdit_bairro.setText("")
        self.lineEdit_bairro.setObjectName("lineEdit_bairro")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(480, 183, 76, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel{\n"
"    color: rgb(216, 231, 255)\n"
"}")
        self.label_8.setObjectName("label_8")
        self.lineEdit_cidade = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_cidade.setGeometry(QtCore.QRect(479, 216, 321, 38))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_cidade.setFont(font)
        self.lineEdit_cidade.setStyleSheet("QLineEdit{\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"    margin-left: 2px solid rgb(49, 48, 98);\n"
"}")
        self.lineEdit_cidade.setText("")
        self.lineEdit_cidade.setObjectName("lineEdit_cidade")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(480, 263, 76, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel{\n"
"    color: rgb(216, 231, 255)\n"
"}")
        self.label_9.setObjectName("label_9")
        self.lineEdit_estado = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_estado.setGeometry(QtCore.QRect(479, 296, 321, 38))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_estado.setFont(font)
        self.lineEdit_estado.setStyleSheet("QLineEdit{\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"    margin-left: 2px solid rgb(49, 48, 98);\n"
"}")
        self.lineEdit_estado.setText("")
        self.lineEdit_estado.setObjectName("lineEdit_estado")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(480, 343, 71, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel{\n"
"    color: rgb(216, 231, 255)\n"
"}")
        self.label_11.setObjectName("label_11")
        self.lineEdit_email = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_email.setGeometry(QtCore.QRect(479, 376, 321, 38))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_email.setFont(font)
        self.lineEdit_email.setStyleSheet("QLineEdit{\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"    margin-left: 2px solid rgb(49, 48, 98);\n"
"}")
        self.lineEdit_email.setText("")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(93, 506, 84, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel{\n"
"    color: rgb(216, 231, 255)\n"
"}")
        self.label_12.setObjectName("label_12")
        self.lineEdit_numero = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_numero.setGeometry(QtCore.QRect(92, 539, 321, 38))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_numero.setFont(font)
        self.lineEdit_numero.setStyleSheet("QLineEdit{\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"    margin-left: 2px solid rgb(49, 48, 98);\n"
"}")
        self.lineEdit_numero.setText("")
        self.lineEdit_numero.setObjectName("lineEdit_numero")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(481, 503, 70, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel{\n"
"    color: rgb(216, 231, 255)\n"
"}")
        self.label_13.setObjectName("label_13")
        self.lineEdit_senha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_senha.setGeometry(QtCore.QRect(480, 536, 321, 38))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_senha.setFont(font)
        self.lineEdit_senha.setStyleSheet("QLineEdit{\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"    margin-left: 2px solid rgb(49, 48, 98);\n"
"}")
        self.lineEdit_senha.setText("")
        self.lineEdit_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(480, 586, 161, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel{\n"
"    color: rgb(216, 231, 255)\n"
"}")
        self.label_14.setObjectName("label_14")
        self.lineEdit_senhaConfirm = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_senhaConfirm.setGeometry(QtCore.QRect(479, 619, 321, 38))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_senhaConfirm.setFont(font)
        self.lineEdit_senhaConfirm.setStyleSheet("QLineEdit{\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"    margin-left: 2px solid rgb(49, 48, 98);\n"
"}")
        self.lineEdit_senhaConfirm.setText("")
        self.lineEdit_senhaConfirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_senhaConfirm.setObjectName("lineEdit_senhaConfirm")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(94, 423, 49, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel{\n"
"    color: rgb(216, 231, 255)\n"
"}")
        self.label_16.setObjectName("label_16")
        self.lineEdit_rua = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_rua.setGeometry(QtCore.QRect(93, 456, 321, 38))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_rua.setFont(font)
        self.lineEdit_rua.setStyleSheet("QLineEdit{\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"    margin-left: 2px solid rgb(49, 48, 98);\n"
"}")
        self.lineEdit_rua.setText("")
        self.lineEdit_rua.setObjectName("lineEdit_rua")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(480, 423, 164, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel{\n"
"    color: rgb(216, 231, 255)\n"
"}")
        self.label_17.setObjectName("label_17")
        self.lineEdit_emailConfirm = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_emailConfirm.setGeometry(QtCore.QRect(479, 456, 321, 38))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_emailConfirm.setFont(font)
        self.lineEdit_emailConfirm.setStyleSheet("QLineEdit{\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"    margin-left: 2px solid rgb(49, 48, 98);\n"
"}")
        self.lineEdit_emailConfirm.setText("")
        self.lineEdit_emailConfirm.setObjectName("lineEdit_emailConfirm")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(94, 343, 52, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel{\n"
"    color: rgb(216, 231, 255)\n"
"}")
        self.label_15.setObjectName("label_15")
        self.lineEdit_cep = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_cep.setGeometry(QtCore.QRect(93, 376, 321, 38))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_cep.setFont(font)
        self.lineEdit_cep.setStyleSheet("QLineEdit{\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"    margin-left: 2px solid rgb(49, 48, 98);\n"
"}")
        self.lineEdit_cep.setText("")
        self.lineEdit_cep.setObjectName("lineEdit_cep")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(430, 110, 30, 561))
        self.line.setStyleSheet("Line{\n"
"\n"
"    color: rgb(216, 231, 255)\n"
"\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(90, 690, 180, 25))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("QLabel{\n"
"    color: rgb(216, 231, 255)\n"
"}")
        self.label_18.setObjectName("label_18")
        self.label_10.raise_()
        self.label_6.raise_()
        self.label.raise_()
        self.lineEdit_nome.raise_()
        self.pushButton_cadastrar.raise_()
        self.label_3.raise_()
        self.dateEdit_nasc.raise_()
        self.label_7.raise_()
        self.label_2.raise_()
        self.lineEdit_cpf.raise_()
        self.label_4.raise_()
        self.lineEdit_complemento.raise_()
        self.label_5.raise_()
        self.lineEdit_bairro.raise_()
        self.label_8.raise_()
        self.lineEdit_cidade.raise_()
        self.label_9.raise_()
        self.lineEdit_estado.raise_()
        self.label_11.raise_()
        self.lineEdit_email.raise_()
        self.label_12.raise_()
        self.lineEdit_numero.raise_()
        self.label_13.raise_()
        self.lineEdit_senha.raise_()
        self.label_14.raise_()
        self.lineEdit_senhaConfirm.raise_()
        self.label_16.raise_()
        self.lineEdit_rua.raise_()
        self.label_17.raise_()
        self.lineEdit_emailConfirm.raise_()
        self.label_15.raise_()
        self.lineEdit_cep.raise_()
        self.line.raise_()
        self.label_18.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Nome Completo *"))
        self.pushButton_cadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.label_3.setText(_translate("MainWindow", "Data de Nascimento *"))
        self.dateEdit_nasc.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.label_7.setText(_translate("MainWindow", "Cadastro"))
        self.label_2.setText(_translate("MainWindow", "CPF *"))
        self.label_4.setText(_translate("MainWindow", "Complemento"))
        self.label_5.setText(_translate("MainWindow", "Bairro *"))
        self.label_8.setText(_translate("MainWindow", "Cidade *"))
        self.label_9.setText(_translate("MainWindow", "Estado *"))
        self.label_11.setText(_translate("MainWindow", "E-mail *"))
        self.label_12.setText(_translate("MainWindow", "Número *"))
        self.label_13.setText(_translate("MainWindow", "Senha *"))
        self.label_14.setText(_translate("MainWindow", "Confirmar senha *"))
        self.label_16.setText(_translate("MainWindow", "Rua *"))
        self.label_17.setText(_translate("MainWindow", "Confirmar E-mail *"))
        self.label_15.setText(_translate("MainWindow", "CEP *"))
        self.label_18.setText(_translate("MainWindow", "* Campo Obrigatório"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
